### ISSUE TITLE
React Native Web: SyntaxError: Missing initializer in const declaration

### ISSUE THREAD

**Issue by whenmoon** [meliorence/react-native-render-html#521]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

When running React Native web and Next JS, after installing react-native-render-html, the app build fails and throws the error:

```
SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (.../node_modules/react-native/Libraries/react-native/react-native-implementation.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (...node_modules/@jsamr/react-native-li/lib/commonjs/MarkedListItem.tsx:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (...node_modules/@jsamr/react-native-li/lib/commonjs/MarkedList.tsx:2:1)
...node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^
```

The issue goes away after removing RNRH

### React Native Information

```sh
System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 21.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.2 - ~/.nvm/versions/node/v12.22.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3, 31.0.0
      System Images: android-21 | Android TV Intel x86 Atom, android-23 | Android TV ARM EABI v7a, android-28 | Android TV Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
```

### RNRH Version

RNRH v6.1.0
RN v0.61.2

### Tested Platforms

- [X] Android
- [ ] iOS
- [X] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [ ] iOS
- [X] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

Cannot provide :(

**Comment by jsamr** [comment]
@whenmoon  Looks like the bug comes from `@jsamr/react-native-li`; I'll take a look!

**Comment by jsamr** [comment]
I took a look at the package tarball, extract it and inspected.

```
/tmp/package ❯ tree lib/commonjs                                                                                                                                                                      17:12:53
lib/commonjs
├── index.js
├── index.js.map
├── MarkedListItem.js
├── MarkedListItem.js.map
├── MarkedList.js
├── MarkedList.js.map
├── MarkerBox.js
├── MarkerBox.js.map
├── shared-types.js
├── shared-types.js.map
├── useMarkedList.js
└── useMarkedList.js.map
```

There is no file named `MarkedList.tsx`. If you want me to help you, you need to provide a reproduction so that I can assess which part of your tooling isn't working as expected, or if I can do anything to enhance integration. **Can't you setup a simple Next.js project with RNRH and provide a MRE?**

**Comment by whenmoon** [comment]
Hi @jsamr thanks for your quick response! I had a quick late night attempt at creating a reproducible example, and whilst I didn't manage to reproduce the exact bug, the build still failed for another reason. This should build by itself:

https://stackblitz.com/edit/github-5xwcny?file=pages/index.js

I wonder if both of these errors are related? I will continue to try and reproduce the exact bug asap.

**Comment by jsamr** [comment]
@whenmoon The next config misses the `__DEV__` environment which is part of the official React Native JS runtimes. You need to inject a global variable. With Webpack, it's pretty easy thanks to the DefinePlugin. See for example

https://github.com/Expensify/App/blob/f8c6120269c66097180d3ebf9152f64f9417c74e/config/webpack/webpack.dev.js#L34-L37

In Next.js, you [can customize the webpack config](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config), so I guess you should be able to find a suitable config, something like (untested): 

```js
// next.config.js
const webpack = require('webpack');

module.exports = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    const nextConfig = {
      ...config,
      plugins: [
        ...config.plugins,
        new webpack.DefinePlugin({
          __REACT_WEB_CONFIG__: JSON.stringify(env),

          // React Native JavaScript environment requires the global __DEV__ variable to be accessible.
          // react-native-render-html uses variable to log exclusively during development.
          // See https://reactnative.dev/docs/javascript-environment
          __DEV__: true,
        }),
      ],
    };
    return config;
  },
};
```

**Comment by jsamr** [comment]
I'm closing due to inactivity, feel free to reopen if you have updates!
